#!/bin/sh
set -e

old_db="$(dirname "$0")/weight.db"
db="$HOME/.local/share/weight-tracker/weight.db"

mkdir -p "$(dirname "$db")"
if [ -e "$old_db" ] && [ ! -e "$db" ]; then
  mv "$old_db" "$db"
fi

cmd() {
  sqlite3 -column "$db" "$@"
}

cmd "
  create table if not exists weights (
    id integer primary key autoincrement not null,
    time datetime not null,
    weight decimal(3,2) not null);"

if [ -n "$1" ]; then
  cmd "insert into weights (time, weight) values (datetime('now'), $1);"
fi

cmd "select strftime('%Y-%m-%d %H:%M', time, 'localtime'), weight from weights order by time desc limit 8;"
